### ISSUE TITLE
"python was not found" error

### ISSUE THREAD

**Issue by Ez4MeGitHub** [quasar098/midi-playground#10]
the "python was not found" error pops up every time

i tried all fixes it doesnt fucking work

**Comment by quasar098** [comment]
some aliases might be python3, py, or python3.X (X being the version number). this happened to me once and i was very pissed that i could not get it to work properly, but we good now. if this doesn't work, idk what is happening on your end

also: add python exec to path!!! this is very important and for some reason python sometimes doesnt do this automatically and so you have to go to the directory in your filesystem that contains the real python executable and add it to path (google it, very easy to do)

**Comment by quasar098** [comment]
whoops accidentally closed and reopened issue

**Comment by Ez4MeGitHub** [comment]
> some aliases might be python3, py, or python3.X (X being the version number). this happened to me once and i was very pissed that i could not get it to work properly, but we good now. if this doesn't work, idk what is happening on your end
> 
> also: **add python exec to path!!!** this is very important and for some reason python sometimes doesnt do this automatically and so you have to go to the directory in your filesystem that contains the real python executable and add it to path (google it, very easy to do)

(in bold characters the text i am replying to) i did it hundreds of times. i havent tried using the python3.x alias but ill try

**Comment by Ez4MeGitHub** [comment]
just tried and it still does not work. maybe you could make an exe to run with an interface to select the midi, so ppl with this error wont have to suffer to make it work? if its possible

**Comment by Ez4MeGitHub** [comment]
ah nvm saw theres a new version, whopee

**Comment by quasar098** [comment]
haha lol
yeah the exec is much easier
