### ISSUE TITLE
Translation to Russian

### ISSUE THREAD

**Issue by Guavvva** [quasar098/midi-playground#101]
"играть"
"настройки"
"репозиторий"
"папка с песнями"
"выйти"
"назад"
"проигрыватель-миди" text (this is the title of the software)
the marquee on the title screen (the moving text that appears underneath the title on the main screen; see translations.py file for english example)
"требуется перезагрузка"

in translations.py you can add this stroke in translation: `"title-marquee": f"""Участники: {contributors}. Хочешь просто смотреть, а не играть? Включи режим "Theatre Mode". Как добавить песню? Перейди по docs/SONGS.md в репозитории чтобы узнать.""".replace("\n", ''),`

if you add this translate, will be cool for russian users :)

**Comment by Guavvva** [comment]
I already tested, it working. I pinned font and updated translations.py to this comment.
[translation.zip](https://github.com/quasar098/midi-playground/files/15223103/translation.zip)

I really want to help this project.

**Comment by quasar098** [comment]
added
