### ISSUE TITLE
4th game build based on 70ee65d

### ISSUE THREAD

**Issue by lucmsilva651** [quasar098/midi-playground#102]
Hi! I have builded this game for you without fixing anything. If you want to put this ZIP in GH releases anyways, download the build release below:

https://www.mediafire.com/file/ub5igqtafna7q73/main.zip/file

And that's it! There is nothing more to say, as I only want to share this build with you. Bye!

**Comment by quasar098** [comment]
oh yeah i have to publish a new build soon

**Comment by quasar098** [comment]
done
