### ISSUE TITLE
Bug with saving metadata

### ISSUE THREAD

**Issue by quareofficial** [quasar098/midi-playground#105]
So, I am trying to save metadata.json for a song. However, when I try to save it, it pops up the "Save as" menu despite the fact that I clicked "Save". I also can't save in zipped folders, so I can't save the metadata, and therefore can't save the song.

![image_2024-05-11_203408187](https://github.com/quasar098/midi-playground/assets/169566012/99608f71-3646-4664-a688-5c6798ecc07a)

**Comment by quasar098** [comment]
this is just a skill issue of you not being able to use windows notepad correctly. 

please try to avoid making "tech support" issues, especially if it is unrelated to the software
