### ISSUE TITLE
Crashes without opening a window 2: Electric Boogaloo

### ISSUE THREAD

**Issue by UniqueName12345** [quasar098/midi-playground#11]
Same MIDI file, same error

If it helps, I use Python 3.9.1

**Comment by quasar098** [comment]
i honestly have no clue but install python from python.org and uninstall the one from windows store if you havent already wait i think you have then i dont know but maybe it is the mido module and i am not sure why this error is happening. try python 3.9.6 maybe? idk that is what i am using

**Comment by UniqueName12345** [comment]
> i honestly have no clue but install python from python.org and uninstall the one from windows store if you havent already wait i think you have then i dont know but maybe it is the mido module and i am not sure why this error is happening. try python 3.9.6 maybe? idk that is what i am using

I did that.

**Comment by quasar098** [comment]
no idea but it is a very obscure error
