### ISSUE TITLE
How can I change the color of the light on the border of the squares in version 4.0, I don't want colored squares

### ISSUE THREAD

**Issue by jjkin123** [quasar098/midi-playground#112]
How can I change the color of the square border glow in version 4.0, I don't want colored squares, I want it like the picture I uploaded, can you please tell me how to do it, thank you!
!
![20240530185144](https://github.com/quasar098/midi-playground/assets/79977644/08b2172a-3cca-4b33-b72e-15b8eddda07e)

**Comment by Akers911** [comment]
Found it how?
