### ISSUE TITLE
New topics regarding translation

### ISSUE THREAD

**Issue by cangerjun** [quasar098/midi-playground#119]
I have translated some of the text before, but there is still a large part of the text that has not been translated.
I previously participated in a translation project where the author extracted all the texts that needed to be translated. (The project is specy's <genshin-music>)
Merge the translated text into the project, and select the language to replace the text after startup.
Can you extract a document like him and let me continue with the translation.

**Comment by quasar098** [comment]
this seems like a good idea but also i do not have the motivation and/or time to do this
if you want to add this feature then you can make a pr and i will probably merge it
