### ISSUE TITLE
Translation to Japanese

### ISSUE THREAD

**Issue by suzuuuuu09** [quasar098/midi-playground#128]
```
"play": "遊ぶ",
"config": "設定",
"contribute": "貢献する",
"open-songs-folder": "楽曲フォルダを開く",
"quit": "終了",

"back": "戻る",
"title": "midi-playground",
"title-marquee": f"""貢献者: {contributors}. 正方形を見ているだけじゃつまらないからゲームをプレイしてみたい？設定でシアターモードをオンにしてみてください。自分の曲を演奏したいけどやり方がわからない？ソースコードのdocs/SONGS.mdを見れば、自分の曲を追加する方法が分かります。""".replace("\n", ''),

"restart-required": "再起動が必要です"
```

This is how we translated it into Japanese.  
Japanese users will be very happy if you add this translation.

[japanese.zip](https://github.com/user-attachments/files/16493515/japanese.zip)

The above file contains an updated translations.py, fonts for Japanese, and an image of the Japanese flag.  
We have already tested it and confirmed that it works.

(This English text may be incorrect due to the use of translations.)

**Comment by quasar098** [comment]
https://github.com/quasar098/midi-playground/pull/130

done
