### ISSUE TITLE
Square bounce

### ISSUE THREAD

**Issue by MrCream-22** [quasar098/midi-playground#129]
Hello, I'm not very experienced with programs, what .py file should I modify for the square bounce to make it more intense and make the square with the colors a little brighter?

**Comment by quasar098** [comment]
color schemes in [config.py](https://github.com/quasar098/midi-playground/blob/master/config.py)

the bounce anim is done [here](https://github.com/quasar098/midi-playground/blob/7f777357939c0c1b27f4a492f43c6f40cb0b76f0/game.py#L118-L126)

to change the bounce intensity, change the lines 124 and 126 to have bigger numbers
