### ISSUE TITLE
[linux] cannot import name 'startfile' from 'os' (main.py)

### ISSUE THREAD

**Issue by TheoCGaming** [quasar098/midi-playground#19]
```
pygame-ce 2.3.0 (SDL 2.26.4, Python 3.11.3)
Traceback (most recent call last):
  File "/home/theocgaming/Programs/midi-playground-master/main.py", line 6, in <module>
    from os import startfile, getcwd
ImportError: cannot import name 'startfile' from 'os' (/usr/lib/python3.11/os.py)
```

**Comment by TheCodingCrafter** [comment]
it may not be linux compatible

**Comment by quasar098** [comment]
it appears to be an error with the python os module on linux. i will fix this as soon as i am back at my computer because linux is very good and i want to put the effort to support it

**Comment by TheoCGaming** [comment]
can confirm on commit [b1f55e4](https://github.com/quasar098/midi-playground/commit/b1f55e41828ebb30555d55d055308327f1759ac3)

**Comment by quasar098** [comment]
turns out that startfile isn't linux compatible, will use a fix from [here](https://stackoverflow.com/questions/17317219/is-there-an-platform-independent-equivalent-of-os-startfile/17317468#17317468) instead

**Comment by quasar098** [comment]
fixed i think

**Comment by quasar098** [comment]
ok i think this issue is fixed and i was able to get a window up with wsl2 but there are a bunch of bugs that i have to go and fix
