### ISSUE TITLE
just make a video mode

### ISSUE THREAD

**Issue by Ez4MeGitHub** [quasar098/midi-playground#22]
just make a video mode

please?

**Comment by TheCodingCrafter** [comment]
enable Theater Mode in options

**Comment by Ez4MeGitHub** [comment]
ah so thats the point

**Comment by quasar098** [comment]
> enable Theater Mode in options

correct. maybe i will make ffmpeg thing with python movie maker library or something so you can auto generate these videos without having to wait for the song to play

**Comment by quasar098** [comment]
> enable Theater Mode in options

correct. maybe i will make ffmpeg thing with python movie maker library or something so you can auto generate these videos without having to wait for the song to play
