### ISSUE TITLE
Map generation fails at exactly 79%

### ISSUE THREAD

**Issue by ilia-21** [quasar098/midi-playground#26]
I have been using [this](https://mega.nz/file/H0wGmSYC#z3ZPi_M9qNpL_tGRzhi5Sz6UP-XTsuZaZIHeXLqaBgY) midi file and every time I try to open it, it crashes at 79%.

I don't see cmd when I open the game, so I can't provide you with an error log.

**Comment by TheCodingCrafter** [comment]
download the source code, go in config.py, near the top there should be a line the says SQUARE_SIZE = 50.
change SQUARE_SIZE to 20, not 50. that should fix it.

**Comment by ilia-21** [comment]
I followed the steps you mentioned, and now the map generation crashes at 95%, without displaying any errors in the console. The only thing I see in the console is a message from pygame community

**Comment by quasar098** [comment]
sometimes the stack is too big and that means there are too many notes to calculate all the bounce positions. try editing out the background notes (usually clef) with musescore software and save it as <name>-mainlines.mid. i dont think there is any way to fix this but i am not sure. it is also unrelated to python max recursion depth

**Comment by quasar098** [comment]
i personally had issues running giornos theme because there were a lot of unnecessary bounce timestamps from background melody, etc

**Comment by TheCodingCrafter** [comment]
try setting max notes in the config to 1-2000 or smth, idk, how much RAM do you have?

**Comment by quasar098** [comment]
i think python can only handle so deep recursion / so large of a stack before it crashes, hence why it doesnt work

**Comment by TheCodingCrafter** [comment]
I wonder how difficult it would be rewrite it without recursion,

would probably involve an infinite loop of some sort.

**Comment by quasar098** [comment]
probably a dfs path searcher would work
