### ISSUE TITLE
[Crash] Timidity error 

### ISSUE THREAD

**Issue by TheoCGaming** [quasar098/midi-playground#28]
pygame-ce 2.3.0 (SDL 2.26.4, Python 3.11.3)
/home/theocgaming/Programs/fix plssssss/midi-playground-master/main.py:25: Warning: PyGame seems to be running through X11 on top of wayland, instead of wayland directly
  real_screen = pygame.display.set_mode(
warning: queue 0x55db9d7224e0 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@33 still attached
  zwp_linux_dmabuf_feedback_v1@31 still attached
  zwp_linux_dmabuf_v1@30 still attached
Traceback (most recent call last):
  File "/home/theocgaming/Programs/fix plssssss/midi-playground-master/main.py", line 194, in <module>
    main()
  File "/home/theocgaming/Programs/fix plssssss/midi-playground-master/main.py", line 150, in main
    song = song_selector.handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/fix plssssss/midi-playground-master/songselector.py", line 168, in handle_event
    pygame.mixer.music.load(BytesIO(f.read()))
pygame.error: Couldn't open timidity.cfg

**Comment by quasar098** [comment]
idk some timidity error probably a linux thing i'm looking into making a custom .bouncingsquare format for convenience and to step away from the midi libraries

**Comment by quasar098** [comment]
https://medium.com/@karthik_ak/pygame-midi-file-issue-on-ubuntu-16-04-2dcfc776ede9
finally found fix i think!!!
