### ISSUE TITLE
It works, but it's mute

### ISSUE THREAD

**Issue by Imadeanaccountjustpostthis** [quasar098/midi-playground#3]
It's entirely mute, everything else works. YES, I HAVE INSTALLED EVERYTHING CORRECTLY BEFORE YOU BRING THAT UP.

**Comment by quasar098** [comment]
please give python version, packages installed, and command used for further debugging

**Comment by quasar098** [comment]
are you there

**Comment by Imadeanaccountjustpostthis** [comment]
Oh, sorry for late response, here
Python: 3.11
Packages: Mido, pygame, tktinter, pywin32 (all latest versions)
I used the example command to test it.

**Comment by quasar098** [comment]
i am not sure why it is mute, but you can try python 3.9

**Comment by StearRubey** [comment]
> i am not sure why it is mute, but you can try python 3.9

I am having the same issue, tried switching to 3.9 and the songs are still mute. Main menu music and sfx when hovering over buttons works fine, just not the songs.

**Comment by Imadeanaccountjustpostthis** [comment]
now it randomly works

**Comment by StearRubey** [comment]
> now it randomly works

what did you do to fix it?

**Comment by quasar098** [comment]
i think it is an issue with midi because the midi engine that pygame uses might not work under certain conditions. i will have to look into it

**Comment by Imadeanaccountjustpostthis** [comment]
> > now it randomly works
> 
> what did you do to fix it?

genuienly don't know, maybe my python was glitching then idk why
