### ISSUE TITLE
Impossible to press Play button on resolution 1280*1024

### ISSUE THREAD

**Issue by gamecube-github** [quasar098/midi-playground#31]
The app itself looks flattened on the sides but hitboxes of buttons are still placed for 16:9. You can make Enter button as a shortcut for Play button

**Comment by quasar098** [comment]
one thing you can do is go into windows settings and change the resolution to 1920x1080, sorry for not making it compatible, usually people are not using small monitor nowadays...

i dont have the motivation to fix everything for 1280*1024, but idk why but it should scale the buttons to account for your monitor resolution, even if the app is flattened on the sides and is weird

**Comment by gamecube-github** [comment]
> one thing you can do is go into windows settings and change the resolution to 1920x1080, sorry for not making it compatible, usually people are not using small monitor nowadays...
> 
> i dont have the motivation to fix everything for 1280*1024, but idk why but it should scale the buttons to account for your monitor resolution, even if the app is flattened on the sides and is weird

if i have monitor with res of 1280*1024 with latest win10 22h2, there's no option of 1920*1080 res, i can provide a screenshot of the square game and resolution settings
![image](https://github.com/quasar098/midi-playground/assets/106277210/1f910e63-3699-4f1c-991a-d651f31a40e0)
![image](https://github.com/quasar098/midi-playground/assets/106277210/79bf9634-f892-45ff-ae51-be39b9519323)
(also don't be confused with russian lang)

**Comment by quasar098** [comment]
any resolution 16:9 should work due to scaling.

1280x1024 doesnt work because it is 5:4 aspect ratio

**Comment by unsightedmetal6** [comment]
Problem still persists on 1920x1080 displays if scaling is not set to 100%. I had it set to 125% while being on 1920x1080, and the button hitboxes were pretty far off until I changed Windows 11's scaling to 100%.

**Comment by lolsaw** [comment]
I have a 1600x900 display on my laptop and i am as well unable to play any song

**Comment by quasar098** [comment]
ok
