### ISSUE TITLE
Im sad because i dont think i can use custom sounds

### ISSUE THREAD

**Issue by MosaicAxolotl** [quasar098/midi-playground#32]
I cant use custom sounds i geuss
![image](https://github.com/quasar098/midi-playground/assets/143361645/abf750bf-5d8a-49ef-b82f-f08b93160eb3)

**Comment by quasar098** [comment]
what operating system are you on

**Comment by quasar098** [comment]
see https://github.com/mido/mido/issues/107

**Comment by quasar098** [comment]
ok
