### ISSUE TITLE
Mac OS isn't supported right?

### ISSUE THREAD

**Issue by JasperSui** [quasar098/midi-playground#33]
Just saw a reel on Instagram playing the "Past Lives" with a bouncing square that was satisfying and I searched for the source but found nothing.

So I am trying to make my version of it by myself, I saw the `pywin32` is in the `requirements.txt`, so I'm assuming that it doesn't support Mac OS currently, right?

Thanks for your amazing work, BTW if you are interested in the reel, [here](https://www.instagram.com/p/CwLqvENN1_g/) it is.

**Comment by quasar098** [comment]
i hate mac users, because all apple products tend to be proprietary garbage and supporting that proprietary garbage is a nightmare. instead, use a windows (preferred) or linux vm

**Comment by JasperSui** [comment]
Alright, thanks for sharing that.
