### ISSUE TITLE
how I created my own MIDIs ?

### ISSUE THREAD

**Issue by kHzzz444** [quasar098/midi-playground#34]
Hello, is there a tool to transform existing music into midi like you did with the basic sounds?

**Comment by quasar098** [comment]
i found the midi files online, there is no tool that works flawlessly to convert mp3 -> midi or wav -> midi because midi is instruments, but mp3/wav/etc is sound waves. sound waves do not contain the timestamps for when the notes happen, so that is why they are unsupported
