### ISSUE TITLE
a website where you can download a lot of songs

### ISSUE THREAD

**Issue by bruce10panda** [quasar098/midi-playground#37]
im working on a website where you can download songs for midi playground, so that you dont need to install songs you don't want to play. if you want to know more just lmk

**Comment by quasar098** [comment]
i was thinking about doing that but also dont make it a static site. if you want a static set of songs that you can update at a given time, making a github gist / github repo just containing the songs is a better idea and will save a lot of your time. if you truly want to make a song hoster where anyone can upload songs, you need a backend (sveltekit?)

**Comment by it7007** [comment]
Hello, please tell me how to make a mid file of a popular song. Thank you very much.

**Comment by quasar098** [comment]
check SONGS.md file in the "docs" folder
