### ISSUE TITLE
Tutorial on how to use very large MIDIs with this program

### ISSUE THREAD

**Issue by gamecube-github** [quasar098/midi-playground#38]
1. Change square speed to 2000 pps (pixels per second)
2. Change bounce min spacing to 33ms
Done! You can now play original RUSH E or other big MIDIs! (loading may take some time)

**Comment by gamecube-github** [comment]
If the app still crashes, let me know, I might experiment with these settings.

**Comment by quasar098** [comment]
ok

**Comment by Kanna-P** [comment]
Reopening because this does not work anymore in 9/18/2024
