### ISSUE TITLE
i got it fixed now nvm

### ISSUE THREAD

**Issue by dingus-bobingus** [quasar098/midi-playground#4]
nevermind i fixed it now

**Comment by quasar098** [comment]
i am working on the gameplay part right now, if you want to help, check the gameplay branch (will be pushing shortly). i'm not sure how the null bytes got into the file, but you will be able to see where they are using a hex editor. i think this is something on your end

**Comment by quasar098** [comment]
more context:
each character in a file is stored as a byte (8 bits, 2 hex characters), and so a null character is usually used to signify the end of a buffer. this can be problematic for python, because python is written in c, and c terminates buffers of variable length with null bytes.

**Comment by dingus-bobingus** [comment]
things happened:

pygame.error: No file 'cruel-angels-thesis.mid' found in working directory '/Users/bingus'.
(i know python but i am new to pygame, i never had a pygame error before)

i seem to have fixed it(i made a dumb mistake), but now how can we make it so we can change it so that i don't need to put the music in the /Users/bingus directory? it might be fixed if it was changed to that it can find the file straight from the samples folder?
(this could help others from having a similar issue, more convenient)

sorry i am causing trouble.
thanks for the help!
