### ISSUE TITLE
Hitboxes for buttons is incorrect on 1366 x 768 sized screens

### ISSUE THREAD

**Issue by jakeyjr** [quasar098/midi-playground#46]
The app is full screen so i cant screenshot using snip. but the hitboxes are completely fucked up. i have a screen size of 1366 x 768, so that might be the problem but im not very sure.

**Comment by jakeyjr** [comment]
https://github.com/quasar098/midi-playground/assets/121777255/870becb3-f4c3-48f3-9102-83f6dd4368fb

i was able to record it, my mouse batteries is running out so here you go

**Comment by MemeGangster** [comment]
I have the same issue, I also can't minitize the game but I think thats's intended (?).

**Comment by quasar098** [comment]
change you res to 1920x1080 temporarily should fix it for most people, planning on adding a windowed mode (maybe if i have the time)

**Comment by Mlaofmd** [comment]
> change you res to 1920x1080 temporarily should fix it for most people, planning on adding a windowed mode (maybe if i have the time)
if i not have monitor with 1920x1080, what then?

**Comment by quasar098** [comment]
go windows settings

**Comment by sayonaraww** [comment]
So ive tried every res known too man and still the hit boxes are completely fucked for me i can even start the game ( rn im using 1920x1080 )

**Comment by skyhhjmk** [comment]
你有尝试过修改config.py中的分辨率设置吗（this is Chinese）

**Comment by it7007** [comment]
> 你尝试过修改config.py中的解析设置吗（这是中文的）

老哥（狗头）

**Comment by Mlaofmd** [comment]
> 你有尝试过修改config.py中的分辨率设置吗（this is Chinese）

oh its works thanks!

**Comment by skyhhjmk** [comment]
nice!



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quasar098/midi-playground"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 晚上9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quasar098/midi-playground] Hitboxes for buttons is incorrect on 1366 x 768 sized screens (Issue #46)





  
你有尝试过修改config.py中的分辨率设置吗（this is Chinese）
  
oh its works thanks!

**Comment by sayonaraww** [comment]
none of the files open

**Comment by quasar098** [comment]
if none of the files open, then you must have some serious issue where you cannot open any file with notepad ? i think that is what you are saying. i cannot help fix windows issues

**Comment by HiimAndrew123** [comment]
its not just you man

**Comment by jakeyjr** [comment]
any updates? i cant even start the damn game!!

**Comment by quasar098** [comment]
> any updates? i cant even start the damn game!!

what errors? any errors? start a new github issue

**Comment by quasar098** [comment]
should be fixed in the newest version which i am about to release
