### ISSUE TITLE
how to import new songs

### ISSUE THREAD

**Issue by SamuelNathanGroupe7** [quasar098/midi-playground#47]
Hello,

i followed the doc to import a new sound. i converted it to .midi but when i launch it the map does anything. i also tried to take a basic sound to make it easier. (an anime played on the piano.)

and also I used a converter it only gave me a .mid file and not 2 files with the mainlines, is it ok ?

**Comment by quasar098** [comment]
wdym convert it to .midi? midi files differ from standard audio files in that midi files are a set of instrument notes but .mp3s and .wavs are sound waves. using a converter will not work. also, what does it mean that "the map does anything"??
