### ISSUE TITLE
Easy fix to big midi files crash

### ISSUE THREAD

**Issue by YF00789** [quasar098/midi-playground#48]
If it wasn't considered at some point already, you just literally need to add
`import sys` to the main.py and then add `sys.setrecursionlimit(limit)` (limit is int) to the main() function
that's it, i built it like that and it works perfectly fine for me

**Comment by quasar098** [comment]
i think i tried that but it kept not working still here i can try it again

**Comment by quasar098** [comment]
already we have set the recursion limit in the utils.py so
