### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by 12-AD** [quasar098/midi-playground#52]
I don't hear any sound. I tried my own song and the songs that already come with the release, all sounds in menus and etc work, just not the song

**Comment by 12-AD** [comment]
i've tried playing the midi file sand they sound fine.

**Comment by 12-AD** [comment]
Update, I tested the first release and I have the same issue

**Comment by quasar098** [comment]
hmm weird what system are you on ? give os, python version, etc

**Comment by 12-AD** [comment]
> hmm weird what system are you on ? give os, python version, etc

using the python version you recommended, windows 11. im gonna try running source code

**Comment by 12-AD** [comment]
i keep getting ModuleNotFoundError: No module named 'moderngl'
and the same for pygame, i have them installed... I've tried multiple interpreters

**Comment by quasar098** [comment]
pip != python, try using python -m pip instead of just pip

**Comment by quasar098** [comment]
closing to inactivity
