### ISSUE TITLE
FATAL ERROR DETECTED: THIS APP FEELS LIKE A NUMB

### ISSUE THREAD

**Issue by NoteSwiper** [quasar098/midi-playground#53]
it displays
```
Failed to extract MSVCP140.dll: decompression resulted in return code -1!
```

**Comment by quasar098** [comment]
it feels like a NUMB, what does that even mean...

try running from source instead of using pyinstaller bundled executable from releases.

**Comment by quasar098** [comment]
closing to incompetence
