### ISSUE TITLE
The resolution is messed up.

### ISSUE THREAD

**Issue by HiimAndrew123** [quasar098/midi-playground#54]
So i opened the game for the first time, and it was very pixelated. When i tried to hover over the play button it didn't work, but when i hovered over the button below, the play button was selected. It is impossible to play the game, talk about changing the config settings. Tried to find a solution online but there arent any. Please fix!!!

**Comment by quasar098** [comment]
change the windows resolution to 1920x1080, or change the source code to have the line with pygame.FULLSCREEN removed

**Comment by HiimAndrew123** [comment]
dude i am using 1080p!!! i cant change the window resolution!
