### ISSUE TITLE
A potential fix for button hitboxes

### ISSUE THREAD

**Issue by merasmus44** [quasar098/midi-playground#56]
The various menu buttons usually have broken hitboxes on different resolution screens. One way to fix this without going through the effort of detecting screen sizes, is to navigate using arrow keys. This could be difficult if you are using a library specifically for the buttons, so if that isn't possible you could map each button to a number and have that activate the function. A lot of games only use arrow keys for menus for this exact reason. I don't know how to merge and do things with github so I have no idea how to upload my version with arrow keys, allthough the one I made is very scuffed.

**Comment by quasar098** [comment]
good idea, but the settings menu is using pygame_gui and idk how to do keyboard for that

i think an easy fix for this common issue would be to simply set the fullscreen initialization to be the resolution of the monitor, so mouse position is 1:1 with the window, but it would also require modifying the menus to work on all resolutions

**Comment by merasmus44** [comment]
I looked through the code and found 1 thing that you can easily implement as a small or temporary fix. when selecting songs, you can get past the mouse offset issue if you use the scrollbar, but you can't press play depending on how bad your offset is. Binding the play button to pygame.K_RETURN would fix that issue, I wouldn't have been able to play without it due to my screen size.

**Comment by quasar098** [comment]
this does not fix the issue at hand

**Comment by quasar098** [comment]
found a fix
