### ISSUE TITLE
Line 2

### ISSUE THREAD

**Issue by Eduplay12** [quasar098/midi-playground#58]
Hi, I was trying to use your most recent code but whenever I run it the problem appears on line 2, here's a photo to show it (https://github.com/quasar098/midi-playground/assets/156555509/66247908-2ba8-4aa8-bf99-208c05b740f6). 

Could you send me an executable with the latest updates or make a third release so we can use it?

The second release is not yet working.

**Comment by quasar098** [comment]
try to run it from the correct directory, what command did you run ?

**Comment by Eduplay12** [comment]
I used what was written in the development guide but it didn't work, maybe it's because I'm new to programming, do you have any step-by-step instructions explaining how to run the code?

**Comment by quasar098** [comment]
no,
