### ISSUE TITLE
Showing only the tiny squares (mini rectangles)

### ISSUE THREAD

**Issue by ingmarinho** [quasar098/midi-playground#63]
Hi,

I was wondering if there's any easy way to just generate the mini pegs/squares/rectangles instead of the whole map? If so could you point me in a direction of how to do this?

Very much appreciated :)

**Comment by quasar098** [comment]
i read your email

replace "hallway" with "background" on this line
https://github.com/quasar098/midi-playground/blob/master/game.py#L128

that is all i believe
