### ISSUE TITLE
Can't press the start button when selecting songs.

### ISSUE THREAD

**Issue by vsdfff** [quasar098/midi-playground#66]
When I was selecting songs I can't press the start button.

**Comment by vsdfff** [comment]
https://github.com/quasar098/midi-playground/assets/106258005/a3552f00-3c40-4cbb-a743-d4f79cbc3b19

**Comment by vsdfff** [comment]
https://github.com/quasar098/midi-playground/assets/106258005/59d8e3e2-317e-4e47-a4e5-b660f83924b6

**Comment by quasar098** [comment]
probably because of monitor resolution issue, change line 12 and 13 in config.py to match your monitor resolution

![image](https://github.com/quasar098/midi-playground/assets/70716985/2bd21cc5-6694-46f8-83cc-ae28df209d03)
