### ISSUE TITLE
I can't get into the game after doing a system restore

### ISSUE THREAD

**Issue by INGCGGGGG** [quasar098/midi-playground#67]
![cd292a0d3478a71fc75b14748cc2d84](https://github.com/quasar098/midi-playground/assets/159463917/44172f7f-7a85-4a0b-b1f0-15f7dad7e10c)
As shown in the figure, my system disk is C disk, the game is installed in E disk, python and other things are installed in C disk, and I still display this after installing pip, pygame and other modules

**Comment by INGCGGGGG** [comment]
Problems that occurred after the system restore, the game ran smoothly before the system restore

**Comment by INGCGGGGG** [comment]
It's still too difficult to learn these codes, and I still haven't fixed it after asking for half an hour in chatgpt...😢😢😢

**Comment by INGCGGGGG** [comment]
By the way, the 'setting.jeson' and 'mainmenu.mp3' files are indeed in the ./assets path, but I don't know how to check this 'directory', and the game has also been reinstalled and still has issues.

**Comment by quasar098** [comment]
are you double clicking on the file or running as administrator? why is your current directory in system32???? maybe try opening up a terminal and navigating to the directory containing the files and then running `python main.py` or something

**Comment by INGCGGGGG** [comment]
> are you double clicking on the file or running as administrator? why is your current directory in system32???? maybe try opening up a terminal and navigating to the directory containing the files and then running `python main.py` or something

Solved because there was python in the computer before the restoration, but there was a problem with this. Thank you
