### ISSUE TITLE
PLZ ADD A MAC BUILD

### ISSUE THREAD

**Issue by Letsygo** [quasar098/midi-playground#69]
windows is garbage and i have a mac so please add a mac build

**Comment by Letsygo** [comment]
#69 lol

**Comment by Letsygo** [comment]
i got issue #69 how lucky

**Comment by quasar098** [comment]
i am banning you for enjoying mac os eww wtf gross

what a weirdo

**Comment by quasar098** [comment]
can't ban you, but it seems that blocking your account prevents you from doing stuff on my repos

**Comment by Coobik1234** [comment]
Hahaha quasar098 your a Sigma
Even I can run it on Linux bruh

**Comment by FireDasher-alt** [comment]
ok this post sucked sorry, and i have came to hate macos because it is so restrictive, the security is too "secure" and barely any software is available, and windows is pretty good

**Comment by FireDasher-alt** [comment]
@quasar098 plz unbann my main
