### ISSUE TITLE
I've made a few more improvements: adding “Resolution” options

### ISSUE THREAD

**Issue by Spring-Forever-with-me** [quasar098/midi-playground#70]
I modified config.py, main.py,configpage.py and now the program runs full screen as a selective feature(resolution of original resolution is Fullscreen) and also changed the position of the options to relative coordinates. But how do I upload them?
![屏幕截图 2024-02-19 171009](https://github.com/quasar098/midi-playground/assets/109018086/854d6a96-4972-4eb7-94f1-6af59a1be316)
![屏幕截图 2024-02-19 171103](https://github.com/quasar098/midi-playground/assets/109018086/757c8c7b-b619-4e59-bb22-f63ea8e3a2d3)

**Comment by quasar098** [comment]
making pull request, see there for updates

**Comment by Spring-Forever-with-me** [comment]
But I don't have permission to upload these files 😂
