### ISSUE TITLE
About shareware

### ISSUE THREAD

**Issue by INGCGGGGG** [quasar098/midi-playground#75]
My friend, can I share your software on the Chinese website bilibili, I will annotate your youtube link and github url in the profile and choose to reprint it in the self-made and reprint of the contribution type, I made some videos to share on bilibili There are many Chinese friends who like your software!(Sorry to bring this up here, I don't know why I can't speak on YouTube)

**Comment by quasar098** [comment]
ok, you can do that, just please dont forget put the github link in the description or wherever is not too hard to see

**Comment by INGCGGGGG** [comment]
thanks,There are already a lot of people making this kind of video on bilibili starting today.This is the link of my video 【https://www.bilibili.com/video/BV11S421A7MP/?spm_id_from=333.337.search-card.all.click.】The link was placed in the comment area below, due to some reason, sometimes we can't browse foreign websites without a VPN, so I uploaded it on the network disk for downloading, and the whole process is free and not profitable.Thank you for making the software! (These English are all using Microsoft Translator, please forgive me if there is any problem with the translation)

**Comment by INGCGGGGG** [comment]
By the way 2902435239@qq.com is my mailbox, I don't know what chat software is used outside of China, so using this old way, if there is a problem with the video I don't find it can contact me here, thank you again
