### ISSUE TITLE
Syncing music

### ISSUE THREAD

**Issue by Lioness100** [quasar098/midi-playground#82]
This is a really cool project! I have a MIDI where the music starts (as fair as I know) right from the beginning, but it's played a tiny bit before the bounces in the game. Is there any methodology to changing `music_offset` to account for this? Or would I just be guessing?

**Comment by quasar098** [comment]
if you want, there is a setting in game called "music offset" or something i cant remember, but you can change that.

i forgot whether positive offset means the song is first, or the music is first, idk

just try like 1000ms and then check which direction it is in, song first or music first, and then guess accordingly until it seems to match up

**Comment by Lioness100** [comment]
Thank you! And how would I get the square to be a bit smaller like in [this video](https://youtu.be/9i4XJT4XXvw?si=eSiTPjOCLyMQDgrz)?

**Comment by quasar098** [comment]
you can change the square size when running the game from source directly i think, or you might be able to change your monitor resolution to a larger one or something
