### ISSUE TITLE
ball

### ISSUE THREAD

**Issue by aryanmmd** [quasar098/midi-playground#84]
![Screenshot 2024-03-29 051822](https://github.com/quasar098/midi-playground/assets/107447324/42e54e99-5afe-4772-b90a-44eee60782f4)
Hi, how can I make one like this?
Is there a project on github that I can use to make something like this?

**Comment by aryanmmd** [comment]
![Uploading Screenshot 2024-03-29 053304.png…]()

**Comment by aryanmmd** [comment]
![Screenshot 2024-03-29 053304](https://github.com/quasar098/midi-playground/assets/107447324/e193f205-6741-4641-acb0-0a05541eacc1)

**Comment by quasar098** [comment]
this is completely separate.
