### ISSUE TITLE
Song Zips are rejected due to metadata.json

### ISSUE THREAD

**Issue by AerosmithTG** [quasar098/midi-playground#85]
![image](https://github.com/quasar098/midi-playground/assets/165431012/947d6795-b12a-45be-8807-312c4697e6cf)
I made sure this wasn't a midi issue by copying over the sound files from one of the existing songs (which work fine), but once I put the file back into the songs folder, the exe will not start and throws this error. I have also copied over songs zips from the most recent version of the raw code (which are not in the compiled version) and no error appears so it seems to be an issue on my side?

**Comment by quasar098** [comment]
do you metadata.json in the zip?

**Comment by aryanmmd** [comment]
Hi, I also had this problem
The problem was with the name-mainlines.mid file

**Comment by AerosmithTG** [comment]
> do you metadata.json in the zip?

There is a metadata.json in the zip, I changed the song name, and which audio files are referenced (but the audio files themselves are identical to ones that work, they simply had their names changed).

**Comment by AerosmithTG** [comment]
> > do you metadata.json in the zip?
> 
> There is a metadata.json in the zip, I changed the song name, and which audio files are referenced (but the audio files themselves are identical to ones that work, they simply had their names changed).

I've now solved the problem, it was a stupid mistake on my part! I was pressing "send to compressed folder" on the unzipped folder rather than for the files themselves, so the zip was 2 layers deep and therefore causing problems! Thanks for the help anyhow!

**Comment by Alex9532** [comment]
Same issue for me! Thanks!
