### ISSUE TITLE
Can't download the requirements

### ISSUE THREAD

**Issue by legoshit** [quasar098/midi-playground#87]
That's all the tittle says
![image](https://github.com/quasar098/midi-playground/assets/165940756/6d4b0d71-d309-40b1-a0be-04ed4e1a8c65)
if you can help, here's my discord (legoshit.)
ty if you help me or even try

**Comment by quasar098** [comment]
you can try downloading a bundled executable in the releases tab

this is not enough error message, send the screenshot of the entire thing

also this doesn't appear to be an error message anyways, just try running the prog now

**Comment by quasar098** [comment]
i think this is a you issue
