### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by leo539** [quasar098/midi-playground#88]
![french](https://github.com/quasar098/midi-playground/assets/65543927/884e644a-0e22-4278-8eeb-8c787bbf1046)

I cant link the translation.py file for some reason (sorry im kinda new to github and Im learning to code)

**Comment by leo539** [comment]
![french](https://github.com/quasar098/midi-playground/assets/65543927/62b30dbf-4314-4cba-9c5f-23ca0aacab5b)

**Comment by quasar098** [comment]
this is just an image of the french flag ?

**Comment by leo539** [comment]
TRANSLATIONS = {
    "english": {
        "font": "poppins-regular.ttf",

        "font-menu-shadow-offset": 9,
        "font-menu-shadow-length-offset": 0,
        "play": "Play",
        "config": "Config",
        "contribute": "Contribute",
        "open-songs-folder": "Open Songs Folder",
        "quit": "Quit",

        "back": "Back",
        "title": "midi-playground",
        "title-marquee": """Contributors: quasar098, TheCodingCrafter, PurpleJuiceBox, sled45, Times0, Spring-Forever-with-me cangerjun, lucmsilva651. Just want to 
watch the square and don't want to play the game? Turn on theatre mode in the config if that is the case. Interested in playing your 
own song but don't know how? Check out docs/SONGS.md in the source code to learn how to add your own songs.""".replace("\n", ''),

        "restart-required": "Restart Required"
    },
    "french": {
        "font" : "poppins-regular.ttf",

        "font-menu-shadow-offset": 9,
        "font-menu-shadow-length-offset": 0,
        "play": "Jouer",
        "config": "Configuration",
        "contribute": "Contribuer",
        "open-songs-folder": "Dossier Chansons",
        "quit": "Quitter",

        "back": "Précédent",
        "title": "midi-playground",
        "title-marquee": """Contribueurs: quasar098, TheCodingCrafter, PurpleJuiceBox, sled45, Times0, Spring-Forever-with-me cangerjun, lucmsilva651. Vous voulez simplement
regarder le carré et ne pas jouer au jeu ? Activez le mode théâtre dans la configuration si tel est le cas. Vous êtes intéressé à jouer votre propre chanson mais ne savez pas comment faire ? 
Consultez docs/SONGS.md dans le code source pour apprendre comment ajouter vos propres chansons.""".replace("\n", ''),

        "restart-required": "Redémarrage nécessaire"

    },
    "brazilian-pt": {
        "font": "poppins-regular.ttf",

        "font-menu-shadow-offset": 9,
        "font-menu-shadow-length-offset": 0,
        "play": "Jogar",
        "config": "Configurações",
        "contribute": "Contribuir",
        "open-songs-folder": "Abrir Pasta de Músicas",
        "quit": "Sair",

        "back": "Voltar",
        "title": "midi-playground",
        "title-marquee": """Contribuintes: quasar098, TheCodingCrafter, PurpleJuiceBox, sled45, Times0, Spring-Forever-with-me, cangerjun, lucmsilva651. 
Quer apenas assistir ao quadrado e não quer jogar o jogo? Se for esse o caso, ative o Modo Teatro nas configurações. Tem interesse em colocar sua própria música, 
mas não sabe como? Consulte docs/SONGS.md no código-fonte para saber como adicionar suas próprias músicas.""".replace("\n", ''),

        "restart-required": "Reinicialização Necessária"
    },
    "spanish": {
        "font": "poppins-regular.ttf",

        "font-menu-shadow-offset": 9,
        "font-menu-shadow-length-offset": 0,
        "play": "Jugar",
        "config": "Configuraciones",
        "contribute": "Contribuir",
        "open-songs-folder": "Carpeta de Músicas",
        "quit": "Salir",

        "back": "Volver",
        "title": "midi-playground",
        "title-marquee": """Colaboradores: quasar098, TheCodingCrafter, PurpleJuiceBox, sled45, Times0, Spring-Forever-with-me, cangerjun, lucmsilva651. 
¿Sólo quieres ver el cuadrado y no jugar el juego? Si es así, activa el Modo Teatro en los ajustes. 
¿Te interesa añadir tu propia música pero no sabes cómo? Consulta docs/SONGS.md en el código fuente para saber cómo puedes poner tu propia música.""".replace("\n", ''),

        "restart-required": "Reinicio Necesario"
    },
    "chinese": {
        "font": "hanyisongjian.ttf",

        "font-menu-shadow-offset": 24,
        "font-menu-shadow-length-offset": -15,
        "play": "开始游戏",
        "config": "设置",
        "contribute": "贡献",
        "open-songs-folder": "打开歌曲文件",
        "quit": "退出",

        "back": "返回",
        "title": "midi游乐场",
        "title-marquee": """贡献者: quasar098, TheCodingCrafter, PurpleJuiceBox, sled45, Times0, Spring-Forever-with-me, cangerjun, lucmsilva651. 快来加入我们！ 
想要看着方块自己动，不想玩游戏？
如果是这样，请在设置中打开剧场模式。
想要播放自己喜欢的歌曲，但不知道如何播放？
查看文件夹中的docs/SONGS.md，了解如何添加自己喜欢的歌曲。""".replace("\n", ''),

        "restart-required": "需要重新启动"
    }
}

**Comment by quasar098** [comment]
i will add these soon

**Comment by quasar098** [comment]
added
