### ISSUE TITLE
Square speed

### ISSUE THREAD

**Issue by CommandGamerPro** [quasar098/midi-playground#9]
The speed of the square is very slow, when it is time for a beat, the square will teleport to the wall

An example video is below:

https://github.com/quasar098/midi-playground/assets/136539568/8482f629-b3df-47c9-bdae-5b74c489b7dd

**Comment by quasar098** [comment]
i think this is either a framerate issue (i have 75hz monitor, made this for 60hz and not below), or a lag issue. it doesn't look like lag, so pls give framerate number for this monitor

**Comment by CommandGamerPro** [comment]
My main display runs at 60hz, and my second one runs at 144hz. This problem persists on both displays.

**Comment by Jakehero4** [comment]
same issue here any fix?

**Comment by quasar098** [comment]
i will fix this i have an idea

**Comment by CommandGamerPro** [comment]
What's your idea?

**Comment by quasar098** [comment]
interpolation between bounces instead of incrementations of position

**Comment by quasar098** [comment]
whoops accidentally closed and reopened issue again
