### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by simpansoftware** [quasar098/midi-playground#93]
Some translations for swedish.

play: spela

config: inställningar

contribute: bidra

open songs folder: öppna låt-mappen

quit: avsluta

back: tillbaka

midi-playground text: midi-playground

the marquee on the title screen: Medhjälpare: {contributors}. Vill du bara se kvadraten och inte vill spela? Sätt på teaterläge i konfigurationerna i så fall. Intresserad i att spela dina egna låtar men du vet inte hur? Kolla docs/SONGS.md i källkoden för att lära dig hur du lägger till dina egna låtar.

restart required: Omstart krävs

**Comment by simpansoftware** [comment]
Added the changes to a pull request

**Comment by quasar098** [comment]
ok
