### ISSUE TITLE
I have made a assembler for song files with Python

### ISSUE THREAD

**Issue by lucmsilva651** [quasar098/midi-playground#95]
Hi, @quasar098! As I don't have any other way to share this with you, I will open this issue for sharing it.

I've made a assembler for the .ZIP files of the songs. It's simple to use. If you can test to see if it works under your machine, i'll be grateful.

Repository link: https://github.com/lucmsilva651/mp-sng

Bye for now!

**Comment by quasar098** [comment]
seems cool
