### ISSUE TITLE
how do i use an mp3 file

### ISSUE THREAD

**Issue by valid5** [quasar098/midi-playground#97]
Change to what?
![image](https://github.com/quasar098/midi-playground/assets/153624919/02b31184-7d8c-45d8-a302-1c0dba4d78c9)

**Comment by quasar098** [comment]
add mp3 instead of midi and change `audio_file`

**Comment by valid5** [comment]
when i do that it just says as an error "not a midi file"
this is my metadata.json
![image](https://github.com/quasar098/midi-playground/assets/153624919/608a35ae-1609-4b5b-9726-4e74e893bf0b)

**Comment by valid5** [comment]
![image](https://github.com/quasar098/midi-playground/assets/153624919/25a77b84-7eb6-419b-bff1-6ca3f37ce792)
